version: '2'

services:
  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://147.45.247.31/default_db
      - POSTGRES_LOGIN=gen_user
      - POSTGRES_PASSWORD=cSCDMyE(/nB52\